project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Ashley Bulseco, Ph.D."
  navbar:
    navbar:
    background: primary
    left:
      - text: "Research"
        href: Research.qmd
    right:
      - icon: github
        href: https://github.com/abulseco
  page-footer:
    center: "Copyright 2024, Ashley Bulseco"
    background: secondary


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

